server:
  port: 8082

spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://pushkargore69_db_user:Pushkar3080@alphaappdb1.mnwmicq.mongodb.net/cb_auth?retryWrites=true&w=majority&appName=cdec-dev}

logging:
  level:
    in.cloudblitz.course: DEBUG


# ${MONGO_URI:mongodb+srv://cloudblitz:redhat123@cloudblitz-cluster.0xef32k.mongodb.net/cb_auth?retryWrites=true&w=majority&appName=cdec-dev}
#mongodb+srv://mongodbuser:<db_password>@alphaappdb.tsiy1fx.mongodb.net/
